### ISSUE TITLE
Question about the data loading

### ISSUE THREAD

**Issue by DuanhaoranCC** [mjDelta/ProteinInterfacePredictionWithGCN#1]
Hello, excuse me，
       your data loading section(utils.py ),When generating the adjacency matrix of an edge or an angle, the shape of the edge is (n, 20, 2),What does 20 * 2 mean? Is a node only has edges with the other 20 nodes? How does this 20 come from? And then there's the
`adj_ distance[i,indices]= np.exp (-edge[i,:,0:1]*edge[i,:,0:1]/(2*sigma*sigma))`Why do you define distance as this equation?

**Comment by mjDelta** [comment]
First, the codes were written for protein interface prediction. So in this application, there were only 20 kinds of amino acids. Besides, '2' in [n, 20, 2] represents the distance and angle among amino acids. </br>**By the way, I don't think the way I handled the distance and angle is the best. More efforts should be taken into consideration.**

**Comment by DuanhaoranCC** [comment]
First of all, thank you for your answer，

I selected the CA atoms in the pdb file. There are N atoms. I calculated the distance between each node and other nodes. If it is less than a certain threshold, it is considered that there are edges. It can be imagined that the number of neighbors of each node is uncertain. How can I control it to 20

**Comment by mjDelta** [comment]
First, I think you can limit your atoms categoty in widespread atoms, like C, O, H, N, P and so on, and special atoms which is critical for your application. </br>
Second, 20 is just special for amino acids. In different situation, you can adjust it depends on your need. </br>
Third, you can set these correponding entries in the adjacent matrix zeros if there is no certain atoms arround your target/center atom, once you have decided the number of atoms category. </br>

**Comment by DuanhaoranCC** [comment]
Thank you for your answer. Your explanation is very useful.
